// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfSs2fL8sLSe0uiru7HJZ05Kh1kQJp9F8',
    appId: '1:152066053549:web:d53077b6b88833c776bd24',
    messagingSenderId: '152066053549',
    projectId: 'my-app-d2e2f',
    authDomain: 'my-app-d2e2f.firebaseapp.com',
    storageBucket: 'my-app-d2e2f.appspot.com',
    measurementId: 'G-6H8C1FZLK7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkn2py8aVfvd71wS-Hbz62xu82uW8a36g',
    appId: '1:152066053549:android:d0b866d6bd19bb1a76bd24',
    messagingSenderId: '152066053549',
    projectId: 'my-app-d2e2f',
    storageBucket: 'my-app-d2e2f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2W1T4Qigx-vJZNqysrqGOrX_0cdzoU2g',
    appId: '1:152066053549:ios:2dec888666be6a6876bd24',
    messagingSenderId: '152066053549',
    projectId: 'my-app-d2e2f',
    storageBucket: 'my-app-d2e2f.appspot.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2W1T4Qigx-vJZNqysrqGOrX_0cdzoU2g',
    appId: '1:152066053549:ios:62f57f7058a29c6d76bd24',
    messagingSenderId: '152066053549',
    projectId: 'my-app-d2e2f',
    storageBucket: 'my-app-d2e2f.appspot.com',
    iosBundleId: 'com.example.myApp.RunnerTests',
  );
}
